name: Generate Breakout SVG

on:
  schedule:
    - cron: "0 0 * * *" # chạy mỗi ngày lúc 00:00 UTC
  workflow_dispatch:

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: ${{ github.repository_owner }}

      - name: Move generated SVGs
        run: |
          mkdir -p images
          mv output/light.svg images/breakout-light.svg
          mv output/dark.svg images/breakout-dark.svg

      - name: Configure Git
        run: |
          git config user.name "Phương Nam"
          git config user.email "nam.dpwork04@gmail.com"

      - name: Commit and push SVGs
        run: |
          git add images/breakout-light.svg images/breakout-dark.svg
          git commit -m "chore: update breakout SVGs" || echo "No changes to commit"
          git push
